version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
  check_status:
    image: 'checker'
    build: 
       context: .
       dockerfile: ./Dockerfile
    volumes:
      - ./log:/log
  jenkins:
      image: "jenkins/jenkins:lts"
      privileged: true
      user: "root"
      ports:
         - "8080:8080"
         - "50000:50000"
      dns:
         - 8.8.8.8
      volumes:
         - "./jenkins:/var/jenkins_home"
         - "/var/run/docker.sock:/var/run/docker.sock"
         - "/etc/resolv.conf:/etc/resolv.conf"
         - "/usr/bin/docker:/usr/bin/docker"
